



version: '3.8'

services:
  angularapp:
    build:
      context: ./AngularCRUD
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - mynetwork

  webapi:
    build:
      context: ./WebAPI/WebAPI
      dockerfile: Dockerfile
    ports:
      - "50306:50306"
    networks:
      - mynetwork
    depends_on:
      - angularapp

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - mynetwork
    depends_on:
      - webapi
    volumes:
      - sql_data:/var/opt/mssql

networks:
  mynetwork:
    driver: bridge

volumes:
  sql_data:

